#! /bin/sh

# hide dot-files
mv ~/dot-files ~/.dot-files

# user scripts to be in path
mkdir -p ~/bin
mkdir -p ~/.config

ln -s ~/.dot-files/scripts ~/bin/scripts
touch ~/.local_zshrc

ln -s ~/.dot-files/configs/zshrc ~/.zshrc
ln -s ~/.dot-files/vim ~/.vim
ln -s ~/.dot-files/vim/vimrc ~/.vimrc
ln -s ~/.dot-files/configs/tmux.conf ~/.tmux.conf
ln -s ~/.dot-files/notes.md ~/notes.md
ln -s ~/.dot-files/configs/nvim ~/.config/nvim
ln -s ~/.dot-files/configs/helix ~/.config/helix

# check if nvim is installed.
if command -v nvim >/dev/null 2>&1; then
	echo "nvim is installed"
else
	echo "nvim is not installed"
	echo "installing nvim"
	curl -o ~/bin/nvim -LO https://github.com/neovim/neovim/releases/latest/download/nvim.appimage
	chmod u+x ~/bin/nvim
fi

# init submodules
git submodule update --init --recursive

git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
~/.fzf/install
# source ~/.zshrc
