#! /usr/bin/env python3

import sys
from rich.console import Console
from rich.markdown import Markdown


fnames = sys.argv[1:]

console = Console()

for fname in fnames:
    if len(fnames) > 1:
        print(f"----------- {fname} ----------")
    with open(fname, 'r') as f:
        content = Markdown(f.read())
        console.print(content)
