#! /usr/bin/python3
import argparse
import re
import os
import json
import subprocess
import datetime


parser = argparse.ArgumentParser(description="Set a push notification reminder")
# parser.add_argument('--app_token', nargs='?', metavar='token', type=str,
#                     help="app token. login to pushover account and get app token")
# parser.add_argument('--user_token', nargs='?', metavar='token', type=str,
# help="user token. login to pushover account and get user token")
# parser.add_argument(
#     "--title",
#     nargs="?",
#     metavar="title",
#     default="Reminder ✅",
#     type=str,
#     help="title of notification",
# )
# parser.add_argument('message', metavar='message', type=str, help="a string to send to client. use quotes!")
parser.add_argument(
    "prompt",
    metavar="time_string",
    nargs="+",
    type=str,
    help="a string to send to client",
)

args = parser.parse_args()
prompt_string = " ".join(args.prompt)


# parse time string
# user can enter a time string like "in 5 minutes" or "at 5:30pm"

# TODO: add ability to accept dates

# if time string is "in 5 minutes"
# then we need to get the current time, add 5 minutes, and then set the reminder
# if time string is "at 5:30pm"
# then we need to just get that time
tre = re.compile(r"(.*)at\s+(\d+):(\d+)\s*(am|pm)")
tre2 = re.compile(r"(.*)in\s+(\d+)\s+(\S+)")
m1 = tre.findall(prompt_string)
m2 = tre2.findall(prompt_string)

print(prompt_string)

current_time = datetime.datetime.now()
future_time = None

if m1:
    mes = m1[0][0]
    h = m1[0][1]
    m = m1[0][2]
    ampm = m1[0][3]

    sp_cmd = "echo sendpush {}".format(mes)
    at_cmd = "at {}:{}{}".format(h, m, ampm)

    ps = subprocess.Popen(sp_cmd.split(), stdout=subprocess.PIPE)
    subprocess.run(at_cmd.split(), stdin=ps.stdout)

elif m2:
    m = m2[0][0]
    v = m2[0][1]
    u = m2[0][2]

    sp_cmd = "echo sendpush {}".format(m)
    at_cmd = "at now + {} {}".format(v, u)

    ps = subprocess.Popen(sp_cmd.split(), stdout=subprocess.PIPE)
    subprocess.run(at_cmd.split(), stdin=ps.stdout)
else:
    print("ERROR: unable to parse time string")
    print("time string must be in the form of 'in 5 minutes' or 'at 5:30pm'")
    exit(1)
